pipelines:
  branches: # Branch-specific pipelines definitions
    master:
        name: Build
        image: node:latest
        caches:
          - node
        script:
          - npm install
          - npm run build
        artifacts:
          # Creating artifacts which can be used in next steps
          - .next/**
          - node_modules/**
  custom: # Pipeline that only runs manually
    production: 
      - step:
          name: Building the app
          image: node:latest
          script:
            - npm install
            - npm run dev build
          artifacts:
            - build/**
      - step:
          name: Deploying the app to S3
          deployment: production
          script:
            - pipe: atlassian/aws-s3-deploy:0.2.4
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: $S3_BUCKET
                ACL: "public-read"
                LOCAL_PATH: "build"